# Generated by Django 4.2.3 on 2023-07-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_tables", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicfield",
            name="type",
            field=models.CharField(
                choices=[("NUMBER", "Number"), ("STRING", "String"), ("BOOLEAN", "Boolean")], max_length=32
            ),
        ),
    ]
